---
#- name: Ensure Dashy group exists
#  group:
#    name: "{{ dashy_group }}"
#    state: present
#
#- name: Ensure Dashy user exists
#  user:
#    name: "{{ dashy_user }}"
#    comment: "{{ dashy_user_comment }}"
#    shell: "{{ dashy_user_shell }}"
#    group: "{{ dashy_group }}"
#    state: present

- name: Clone Dashy repository
  git:
    force: true
    repo: https://github.com/Lissy93/dashy.git
    clone: true
    depth: 1
    dest: "{{ dashy_install_dir }}"
    version: "{{ dashy_version }}"

- name: Copy settings
  template:
    src: dashy_conf.yml.j2
    dest: "{{ dashy_install_dir }}/public/conf.yml"
    mode: 0644
  register: copy_output
