---
- name: Converge
  hosts: all

  roles:
    - role: oefenweb.nodejs
      vars:
        nodejs_version: nodejs-v14x
    - role: oefenweb.yarn
    - role: geerlingguy.git
    - role: pmoscode.dashy
    #- role: ansible-role-dashy
